### ISSUE TITLE
Markdown violations in Node operators pages

### ISSUE THREAD

**Issue by RodinGolodin** [axieinfinity/ronin-documentation#168]
### Code of Conduct

- [X] I've read and agree to the Ronin documentation project's [Code of Conduct](https://github.com/axieinfinity/ronin-document/blob/main/CODE_OF_CONDUCT.md)

### What page on docs.roninchain.com is affected?

The Markdown linter found violations in the Node operators pages: https://github.com/axieinfinity/ronin-document/tree/main/docs/node-operators

We should fix these violations for overall consistency.

### What parts of the page would you like to see updated?

- Add blank lines around headers
- Add blank lines around lists
- Occasional trailing spaces

**Comment by Sdaewa** [comment]
Can I take care of this issue?

**Comment by RodinGolodin** [comment]
@Sdaewa You're more than welcome to do so!

**Comment by RodinGolodin** [comment]
I approved and merged the PR. Closing the issue. Thank you @Sdaewa !
