### ISSUE TITLE
Grammar issues and typos on some pages in the Basics section

### ISSUE THREAD

**Issue by chaaals** [axieinfinity/ronin-documentation#175]
### Code of Conduct

- [X] I've read and agree to the Ronin documentation project's [Code of Conduct](https://github.com/axieinfinity/ronin-documentation/blob/main/CODE_OF_CONDUCT.md)

### What page on docs.roninchain.com is affected?

These are some of the pages in the Basic section where I saw grammar issues and typos:
https://docs.roninchain.com/docs/basics/tokenomics
https://docs.roninchain.com/docs/basics/rewards
https://docs.roninchain.com/docs/basics/dapps/ronin-bridge

### What parts of the page would you like to see updated?

**Tokenomics**
![image](https://user-images.githubusercontent.com/70326902/233333128-16f30ffe-7ab6-49ca-b0ff-80b47a1febfa.png)
- Should be updated to `These rewards ...`

**dApps - Bridge**
![image](https://user-images.githubusercontent.com/70326902/233333999-e1a3dd3a-dd28-42c0-9fa2-010879fc3cf9.png)
- Typo

**Rewards**
![image](https://user-images.githubusercontent.com/70326902/233334767-cf083a32-8642-4974-a3d4-a013ca93332f.png)
I was thinking if this could be rephrased to something like:
`On Ronin, token holders stake their RON to participate in validator selection and in exchange, token holders earn rewards for their service.`

### Additional information
If approved, I would like to work on this issue.

**Comment by RodinGolodin** [comment]
@chaaals Nice catch, approved!

**Comment by chaaals** [comment]
cool! @RodinGolodin opened a PR for it :))

**Comment by RodinGolodin** [comment]
PR merged, thank you for your contribution @chaaals 🙇
